apiVersion: v1
kind: Service
metadata: 
  name: db
  labels: 
    app: voting-app
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: voting-app
    type: db
