apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: voting-app
    type: redis-service
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: voting-app
    type: cache
