apiVersion: v1
kind: Service
metadata: 
  name: result-service
  labels: 
    app: voting-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30005
  selector:
    app: voting-app
    type: front-end
    name: result
