apiVersion: v1
kind: Service
metadata: 
  name: voting-service
  labels: 
    app: voting-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30009
  selector:
    app: voting-app
    type: front-end
    name: voting
