apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    app: voting-app
    type: db
spec:
  containers:
    - name: postgres
      image: postgres:12
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"