apiVersion: apps/v1
kind: Deployment
metadata: 
  name: redis-deployment
  labels:
    app: redis-app
spec:
  template:
    metadata:
      name: redis
      labels:
        app: voting-app
        type: cache
    spec:
      containers:
        - name: redis
          image: redis:6.0
          ports:
            - containerPort: 6379
  replicas: 2
  selector:
    matchLabels:
      app: voting-app
      type: cache