apiVersion: v1
kind: Pod
metadata:
  name: result-app
  labels:
    app: voting-app
    type: front-end
    name: result
spec:
  containers:
    - name: result-app
      image: dockersamples/examplevotingapp_result:before
      ports:
        - containerPort: 80