apiVersion: v1
kind: Service
metadata: 
  name: voting-service
  labels: 
    app: voting-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: voting-app
    type: front-end
    name: voting
