apiVersion: apps/v1
kind: Deployment
metadata: 
  name: voting-app-deployment
  labels:
    app: voting-app
spec:
  template:
    metadata:
      name: voting-app
      labels:
        app: voting-app
        type: front-end
        name: voting
    spec:
        containers:
           - name: voting-app
             image: kodekloud/examplevotingapp_vote:v1
             ports:
              - containerPort: 80
  replicas: 3
  selector:
    matchLabels:
      app: voting-app
      type: front-end
      name: voting
