apiVersion: apps/v1
kind: Deployment
metadata: 
  name: worker-app-deployment
  labels:
    app: voting-app
spec:
  template:
    metadata:
      name: worker
      labels:
        app: voting-app
        type: worker
    spec:
       containers:
         - name: worker
           image: kodekloud/examplevotingapp_worker:v1
  replicas: 2
  selector:
    matchLabels:
        app: voting-app
        type: worker
